In [1]:
import pandas as pd

# Notebook para consolidação das tabelas
- Constroí a tabela de sumário e a tabela de resultados por classe

## Constroí dataframe de sumário dos modelos

In [2]:
data_summary = pd.read_json("/home/leo/Documentos/mestrado/DeepWeeds-Mobile/results_new/models_summary.json", orient="index")
data_summary.drop(columns=["file", "path",'trainable','non_trainable','memory_MB', 'dtype_breakdown','input_h', 'input_w', 'FLOPs', 'bench_batch',
       'bench_runs', 'bench_warmup','lat_ms_p50', 'lat_ms_p95','fps_p50', 'fps_p95','inputs', 'outputs'], inplace=True)
data_summary = data_summary.reset_index(drop=True)
data_summary.rename(columns={
    "total": "Parâmetros (M)",
    "lat_ms_mean": "Latência Média (ms)",
    "fps_mean": "FPS Média",
    "model_name": "Modelo"
}, inplace=True)
data_summary["Parâmetros (M)"] = data_summary["Parâmetros (M)"] / 1_000_000
data_summary["Parâmetros (M)"] = data_summary["Parâmetros (M)"].round(2)
data_summary["Latência Média (ms)"] = data_summary["Latência Média (ms)"].round(2)
data_summary["GFLOPs"] = data_summary["GFLOPs"].round(2)
data_summary["GMAC"] = data_summary["GMAC"].round(2)
data_summary["FPS Média"] = data_summary["FPS Média"].round(2)


data_summary

,Parâmetros (M),GFLOPs,GMAC,Latência Média (ms),FPS Média,Modelo
0,6.25,1.46,0.73,3.37,296.96,efficientnetv2b0
1,7.26,2.42,1.21,4.16,240.62,efficientnetv2b1
2,9.13,3.44,1.72,4.67,214.26,efficientnetv2b2
3,13.33,6.09,3.05,6.28,159.34,efficientnetv2b3
4,22.33,11.47,5.73,6.99,143.14,head
5,22.33,11.47,5.73,7.74,129.22,inceptionv3
6,2.59,0.61,0.31,2.73,366.71,mobilenetv2
7,3.24,0.44,0.22,2.66,375.52,mobilenetv3large
8,1.09,0.12,0.06,2.22,451.43,mobilenetv3small
9,4.54,1.15,0.57,9.62,104.00,nasnetmobile
10,43.15,14.43,7.22,9.46,105.75,resnet101v2
11,24.11,7.75,3.88,5.98,167.34,resnet50

## Constroí a tabela de resultados por classe

In [6]:
df = pd.read_csv('/home/leo/Documentos/mestrado/DeepWeeds-Mobile/results_new/results.csv')
df_classes = df.pivot_table(
    index="model",
    columns="class",
    values=["precision", "recall", "f1"]
)
df = df.rename(columns={"model": "Modelo", 
                        "class": "Classe", 
                        "precision": "Precisão", 
                        "recall": "Recall", 
                        "f1": "F1"})
df_classes.to_csv("/home/leo/Documentos/mestrado/DeepWeeds-Mobile/results_new/results_byclass.csv", index=True)
df_classes

                      f1                                                  \
class                  0       1       2       3       4       5       6
model
efficientnetv2b0  0.8624  0.8598  0.9423  0.8571  0.9136  0.9196  0.8968
efficientnetv2b1  0.8630  0.8978  0.9679  0.8339  0.9141  0.9316  0.9212
efficientnetv2b2  0.8701  0.9333  0.9548  0.8681  0.9207  0.9533  0.9294
efficientnetv2b3  0.8793  0.9295  0.9615  0.8809  0.9342  0.9577  0.9118
inceptionv3       0.8263  0.8831  0.9145  0.7734  0.8802  0.9132  0.8810
mobilenetv2       0.7670  0.8581  0.9246  0.7842  0.8649  0.9205  0.8204
mobilenetv3large  0.8698  0.9367  0.9481  0.9352  0.9288  0.9474  0.9350
mobilenetv3small  0.8036  0.8302  0.9191  0.8425  0.9091  0.9257  0.8639
nasnetmobile      0.7554  0.8000  0.9043  0.6807  0.8882  0.8803  0.8343
resnet101v2       0.8135  0.8875  0.9457  0.8920  0.9048  0.9158  0.8976
resnet50          0.7805  0.8843  0.9072  0.8842  0.9006  0.9347  0.9415

                                 precision  ...          recall          \
class                  7       8         0  ...       8       0       1
model                                       ...
efficientnetv2b0  0.8188  0.9494    0.8868  ...  0.9515  0.8393  0.8868
efficientnetv2b1  0.8063  0.9551    0.8457  ...  0.9594  0.8810  0.9119
efficientnetv2b2  0.8317  0.9578    0.8280  ...  0.9686  0.9167  0.9245
efficientnetv2b3  0.8475  0.9650    0.8500  ...  0.9615  0.9107  0.9119
inceptionv3       0.8014  0.9322    0.8313  ...  0.9141  0.8214  0.8553
mobilenetv2       0.7508  0.9244    0.7337  ...  0.9362  0.8036  0.8365
mobilenetv3large  0.8707  0.9656    0.8647  ...  0.9663  0.8750  0.9308
mobilenetv3small  0.7709  0.9298    0.8036  ...  0.9150  0.8036  0.8302
nasnetmobile      0.7527  0.9129    0.7871  ...  0.8940  0.7262  0.8176
resnet101v2       0.8232  0.9513    0.8365  ...  0.9523  0.7917  0.8931
resnet50          0.8077  0.9486    0.8000  ...  0.9455  0.7619  0.9371


class                  2       3       4       5       6       7       8
model
efficientnetv2b0  0.9545  0.7987  0.9308  0.9408  0.9441  0.7974  0.9473
efficientnetv2b1  0.9805  0.7338  0.9371  0.9408  0.9441  0.8431  0.9510
efficientnetv2b2  0.9610  0.8117  0.9497  0.9408  0.9814  0.8562  0.9473
efficientnetv2b3  0.9740  0.7922  0.9371  0.9671  0.9627  0.8170  0.9685
inceptionv3       0.9026  0.6429  0.9245  0.9342  0.9193  0.7386  0.9510
mobilenetv2       0.9156  0.7078  0.9057  0.9145  0.9503  0.7386  0.9129
mobilenetv3large  0.9481  0.8896  0.9434  0.9474  0.9379  0.9020  0.9649
mobilenetv3small  0.9221  0.7468  0.9434  0.9013  0.9068  0.6928  0.9451
nasnetmobile      0.8896  0.5260  0.8994  0.8947  0.9379  0.6863  0.9327
resnet101v2       0.9610  0.8312  0.9560  0.8947  0.9255  0.8366  0.9502
resnet50          0.8571  0.8182  0.9686  0.8947  0.9503  0.8235  0.9517

[11 rows x 27 columns]

## Faz o merge da tabela resultados Macro

In [7]:
df = pd.read_csv('/home/leo/Documentos/mestrado/DeepWeeds-Mobile/results_new/results_macro.csv')
df["model"] = df["model"].str.replace("report_", "", regex=False)
df_macro = df.rename(columns={"model": "Modelo", 
                        "accuracy": "Acurácia Média", 
                        "macro_precision": "Precisão Média", 
                        "macro_recall": "Recall Médio", 
                        "macro_f1": "F1 Médio"})
df_macro

,Modelo,Acurácia Média,Precisão Média,Recall Médio,F1 Médio,weighted_precision,weighted_recall,weighted_f1,support_total
0,mobilenetv2,0.8812,0.8448,0.8539,0.8461,0.8860,0.8812,0.8818,2626
1,inceptionv3,0.8991,0.8900,0.8544,0.8673,0.9007,0.8991,0.8971,2626
2,mobilenetv3small,0.8964,0.8837,0.8547,0.8661,0.8974,0.8964,0.8951,2626
3,efficientnetv2b2,0.9334,0.9079,0.9210,0.9133,0.9355,0.9334,0.9337,2626
4,nasnetmobile,0.8679,0.8529,0.8123,0.8232,0.8712,0.8679,0.8643,2626
5,efficientnetv2b3,0.9402,0.9251,0.9157,0.9186,0.9414,0.9402,0.9398,2626
6,efficientnetv2b1,0.9250,0.8997,0.9026,0.8990,0.9269,0.9250,0.9248,2626
7,mobilenetv3large,0.9440,0.9270,0.9266,0.9263,0.9448,0.9440,0.9442,2626
8,efficientnetv2b0,0.9181,0.8910,0.8933,0.8911,0.9187,0.9181,0.9178,2626
9,resnet101v2,0.9193,0.8936,0.8933,0.8924,0.9202,0.9193,0.9192,2626
10,resnet50,0.9155,0.8948,0.8848,0.8877,0.9175,0.9155,0.9154,2626

In [8]:
df_final = df_macro.merge(
    data_summary,
    on="Modelo",
    how="inner"
)
df_final

,Modelo,Acurácia Média,Precisão Média,Recall Médio,F1 Médio,weighted_precision,weighted_recall,weighted_f1,support_total,Parâmetros (M),GFLOPs,GMAC,Latência Média (ms),FPS Média
0,mobilenetv2,0.8812,0.8448,0.8539,0.8461,0.8860,0.8812,0.8818,2626,2.59,0.61,0.31,2.73,366.71
1,inceptionv3,0.8991,0.8900,0.8544,0.8673,0.9007,0.8991,0.8971,2626,22.33,11.47,5.73,7.74,129.22
2,mobilenetv3small,0.8964,0.8837,0.8547,0.8661,0.8974,0.8964,0.8951,2626,1.09,0.12,0.06,2.22,451.43
3,efficientnetv2b2,0.9334,0.9079,0.9210,0.9133,0.9355,0.9334,0.9337,2626,9.13,3.44,1.72,4.67,214.26
4,nasnetmobile,0.8679,0.8529,0.8123,0.8232,0.8712,0.8679,0.8643,2626,4.54,1.15,0.57,9.62,104.00
5,efficientnetv2b3,0.9402,0.9251,0.9157,0.9186,0.9414,0.9402,0.9398,2626,13.33,6.09,3.05,6.28,159.34
6,efficientnetv2b1,0.9250,0.8997,0.9026,0.8990,0.9269,0.9250,0.9248,2626,7.26,2.42,1.21,4.16,240.62
7,mobilenetv3large,0.9440,0.9270,0.9266,0.9263,0.9448,0.9440,0.9442,2626,3.24,0.44,0.22,2.66,375.52
8,efficientnetv2b0,0.9181,0.8910,0.8933,0.8911,0.9187,0.9181,0.9178,2626,6.25,1.46,0.73,3.37,296.96
9,resnet101v2,0.9193,0.8936,0.8933,0.8924,0.9202,0.9193,0.9192,2626,43.15,14.43,7.22,9.46,105.75
10,resnet50,0.9155,0.8948,0.8848,0.8877,0.9175,0.9155,0.9154,2626,24.11,7.75,3.88,5.98,167.34

## Faz o merge da tabela benchmark com os dataset real
- Note que há as métricas [REAL] que foram utilizados o dataset do deepweeds
- as outras métricas de FPS e latência utilizam Dummy

In [10]:
data_bench = pd.read_csv("/home/leo/Documentos/mestrado/DeepWeeds-Mobile/bench_out/bench_all.csv")
data_bench = data_bench.drop(columns=["file", "path", "input_h", "input_w", "batch" ,"steps",'lat_ms_p50', 'lat_ms_p95','fps_p50', 'fps_p95', 'preprocess_embutido'])
data_bench.rename(columns={
    "model_key": "Modelo",
    "lat_ms_mean": "[Real] Latência Média (ms)",
    "fps_mean": "[Real] FPS Média"
}, inplace=True)
data_bench["[Real] Latência Média (ms)"] = data_bench["[Real] Latência Média (ms)"].round(2)

In [11]:
summary = data_bench.merge(
    df_final,
    on="Modelo",
    how="inner"

)
summary.to_csv("/home/leo/Documentos/mestrado/DeepWeeds-Mobile/results_new/summary_results.csv", index=False)