In [2]:
import pandas as pd

# Notebook para consolidação das tabelas
- Constroí a tabela de sumário e a tabela de resultados por classe

## Constroí dataframe de sumário dos modelos

In [63]:
data_summary = pd.read_json("/home/leo/Documentos/mestrado/DeepWeeds-Mobile/models_summary.json", orient="index")
data_summary.drop(columns=["file", "path",'trainable','non_trainable','memory_MB', 'dtype_breakdown','input_h', 'input_w', 'FLOPs', 'bench_batch',
       'bench_runs', 'bench_warmup','lat_ms_p50', 'lat_ms_p95','fps_p50', 'fps_p95','inputs', 'outputs'], inplace=True)
data_summary = data_summary.reset_index(drop=True)
data_summary.rename(columns={
    "total": "Parâmetros (M)",
    "lat_ms_mean": "Latência Média (ms)",
    "fps_mean": "FPS Média",
    "model_name": "Modelo"
}, inplace=True)
data_summary["Parâmetros (M)"] = data_summary["Parâmetros (M)"] / 1_000_000
data_summary["Parâmetros (M)"] = data_summary["Parâmetros (M)"].round(2)
data_summary["Latência Média (ms)"] = data_summary["Latência Média (ms)"].round(2)
data_summary["GFLOPs"] = data_summary["GFLOPs"].round(2)
data_summary["GMAC"] = data_summary["GMAC"].round(2)
data_summary["FPS Média"] = data_summary["FPS Média"].round(2)


data_summary

,Parâmetros (M),GFLOPs,GMAC,Latência Média (ms),FPS Média,Modelo
0,6.25,1.46,0.73,3.49,286.75,efficientnetv2b0
1,7.26,2.42,1.21,4.14,241.30,efficientnetv2b1
2,9.13,3.44,1.72,4.73,211.43,efficientnetv2b2
3,13.33,6.09,3.05,6.29,158.98,efficientnetv2b3
4,22.33,11.47,5.73,7.29,137.26,inceptionv3
5,2.59,0.61,0.31,2.47,405.35,mobilenetv2
6,3.24,0.44,0.22,2.56,390.31,mobilenetv3large
7,1.09,0.12,0.06,2.06,485.96,mobilenetv3small
8,4.54,1.15,0.57,9.13,109.56,nasnetmobile
9,43.15,14.43,7.22,9.41,106.25,resnet101v2
10,24.11,7.75,3.88,6.10,164.02,resnet50

## Constroí a tabela de resultados por classe

In [ ]:
df = pd.read_csv('results.csv')
df_classes = df.pivot_table(
    index="model",
    columns="class",
    values=["precision", "recall", "f1"]
)
df = df.rename(columns={"model": "Modelo", 
                        "class": "Classe", 
                        "precision": "Precisão", 
                        "recall": "Recall", 
                        "f1": "F1"})
df_classes.to_csv("results_byclass.csv", index=True)
df_classes

                      f1                                                  \
class                  0       1       2       3       4       5       6
model
efficientnetv2b0  0.8467  0.8789  0.9414  0.8214  0.8947  0.9233  0.9064
efficientnetv2b1  0.8597  0.9085  0.9614  0.8379  0.9105  0.9388  0.9333
efficientnetv2b2  0.8860  0.9278  0.9626  0.8843  0.9091  0.9541  0.9366
efficientnetv2b3  0.8685  0.9427  0.9710  0.8841  0.9085  0.9584  0.9408
inceptionv3       0.8391  0.9037  0.9342  0.8233  0.8811  0.9309  0.8991
mobilenetv2       0.7529  0.8202  0.8900  0.6892  0.7976  0.8983  0.8091
mobilenetv3large  0.8262  0.9014  0.9195  0.9048  0.9088  0.9292  0.9342
mobilenetv3small  0.8217  0.8190  0.9159  0.7911  0.8933  0.9311  0.8876
nasnetmobile      0.7781  0.8413  0.8908  0.7280  0.8723  0.9079  0.8840
resnet101v2       0.8134  0.8606  0.9456  0.8720  0.8876  0.9320  0.9287
resnet50          0.8097  0.9074  0.8993  0.8470  0.8424  0.9358  0.9193

                                 precision  ...          recall          \
class                  7       8         0  ...       8       0       1
model                                       ...
efficientnetv2b0  0.8013  0.9459    0.8665  ...  0.9410  0.8279  0.8871
efficientnetv2b1  0.8193  0.9540    0.8649  ...  0.9512  0.8546  0.9185
efficientnetv2b2  0.8399  0.9585    0.8732  ...  0.9655  0.8991  0.9467
efficientnetv2b3  0.8309  0.9634    0.8647  ...  0.9580  0.8724  0.9279
inceptionv3       0.8185  0.9404    0.8506  ...  0.9280  0.8279  0.9122
mobilenetv2       0.7162  0.9090    0.7298  ...  0.9038  0.7774  0.7649
mobilenetv3large  0.8093  0.9516    0.8274  ...  0.9560  0.8249  0.9028
mobilenetv3small  0.7770  0.9323    0.8604  ...  0.9148  0.7864  0.8088
nasnetmobile      0.7599  0.9161    0.8218  ...  0.8944  0.7389  0.8307
resnet101v2       0.8128  0.9449    0.8323  ...  0.9415  0.7953  0.8997
resnet50          0.7982  0.9471    0.8869  ...  0.9469  0.7448  0.9216


class                  2       3       4       5       6       7       8
model
efficientnetv2b0  0.9353  0.7492  0.9060  0.9340  0.9472  0.7934  0.9510
efficientnetv2b1  0.9676  0.7492  0.9248  0.9373  0.9348  0.8623  0.9568
efficientnetv2b2  0.9579  0.8339  0.9248  0.9604  0.9627  0.8689  0.9517
efficientnetv2b3  0.9741  0.8078  0.9342  0.9505  0.9627  0.8295  0.9689
inceptionv3       0.9191  0.7362  0.9060  0.9340  0.9130  0.7836  0.9531
mobilenetv2       0.8770  0.5635  0.8464  0.8746  0.9410  0.6951  0.9143
mobilenetv3large  0.9612  0.8827  0.9216  0.9307  0.9472  0.8000  0.9473
mobilenetv3small  0.9159  0.6971  0.9185  0.9142  0.9317  0.7311  0.9506
nasnetmobile      0.8447  0.6059  0.8777  0.9109  0.9348  0.7574  0.9389
resnet101v2       0.9288  0.8208  0.9279  0.9043  0.9099  0.8328  0.9484
resnet50          0.8382  0.7752  0.9467  0.9142  0.9379  0.8754  0.9473

[11 rows x 27 columns]

## Faz o merge da tabela resultados Macro

In [80]:
df = pd.read_csv('results_macro.csv')
df["model"] = df["model"].str.replace("report_", "", regex=False)
df_macro = df.rename(columns={"model": "Modelo", 
                        "accuracy": "Acurácia Média", 
                        "macro_precision": "Precisão Média", 
                        "macro_recall": "Recall Médio", 
                        "macro_f1": "F1 Médio"})
df_macro

,Modelo,Acurácia Média,Precisão Média,Recall Médio,F1 Médio,weighted_precision,weighted_recall,weighted_f1,support_total
0,mobilenetv2,0.8563,0.8260,0.8060,0.8092,0.8610,0.8563,0.8549,5253
1,inceptionv3,0.9117,0.8984,0.8761,0.8856,0.9117,0.9117,0.9107,5253
2,mobilenetv3small,0.8966,0.8811,0.8505,0.8632,0.8962,0.8966,0.8949,5253
3,efficientnetv2b2,0.9362,0.9137,0.9229,0.9177,0.9373,0.9362,0.9364,5253
4,nasnetmobile,0.8784,0.8661,0.8266,0.8420,0.8788,0.8784,0.8760,5253
5,efficientnetv2b3,0.9395,0.9253,0.9142,0.9187,0.9400,0.9395,0.9392,5253
6,efficientnetv2b1,0.9265,0.9078,0.9007,0.9026,0.9277,0.9265,0.9262,5253
7,mobilenetv3large,0.9227,0.8952,0.9021,0.8983,0.9230,0.9227,0.9227,5253
8,efficientnetv2b0,0.9134,0.8900,0.8812,0.8845,0.9133,0.9134,0.9127,5253
9,resnet101v2,0.9141,0.8939,0.8853,0.8886,0.9155,0.9141,0.9142,5253
10,resnet50,0.9096,0.8870,0.8779,0.8785,0.9145,0.9096,0.9099,5253

In [ ]:
df_final = df_macro.merge(
    data_summary,
    on="Modelo",
    how="inner"
)
df_final

## Faz o merge da tabela benchmark com os dataset real
- Note que há as métricas [REAL] que foram utilizados o dataset do deepweeds
- as outras métricas de FPS e latência utilizam Dummy

In [103]:
data_bench = pd.read_csv("bench_out/bench_all.csv")
data_bench = data_bench.drop(columns=["file", "path", "input_h", "input_w", "batch" ,"steps",'lat_ms_p50', 'lat_ms_p95','fps_p50', 'fps_p95', 'preprocess_embutido'])
data_bench.rename(columns={
    "model_key": "Modelo",
    "lat_ms_mean": "[Real] Latência Média (ms)",
    "fps_mean": "[Real] FPS Média"
}, inplace=True)
data_bench["[Real] Latência Média (ms)"] = data_bench["[Real] Latência Média (ms)"].round(2)

In [ ]:
summary = data_bench.merge(
    df_final,
    on="Modelo",
    how="inner"

)
summary.to_csv("summary_results.csv", index=False)